name: Deploy to Production

on:
  push:
    branches:
      - main11
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the version of Node.js you need

      - name: Install dependencies
        run: npm install -f

      - name: Build the React app
        run: npm run build
  
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/fleetblox_db.pem
          chmod 600 ~/.ssh/fleetblox_db.pem

      - name: Deploy to EC2 
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/fleetblox_db.pem ubuntu@ec2-15-156-8-35.ca-central-1.compute.amazonaws.com '
            cd /home/ubuntu/Pre-launching-landing-
            sudo chmod +x deploy.sh
            sudo ./deploy.sh
          '
